//
//  MockData.swift
//  GGiriGGiri
//
//  Created by 안상희 on 2022/07/03.
//  Copyright © 2022 dvHuni. All rights reserved.
//

import Foundation

struct MockData {
    static let main: [MainSection] = [
            .deadLine([
                GifticonCard(sprinkleTime: "2022.08.12",
                              gifticonInfo: Gifticon(id: 0,
                                                     brand: "스타벅스",
                                                     name: "아메리카노",
                                                     expirationDate: "2022.08.15",
                                                     category: .cafe),
                              numberOfParticipants: 12342,
                              isParticipating: false),
                 GifticonCard(sprinkleTime: "2022.08.13",
                              gifticonInfo: Gifticon(id: 1,
                                                     brand: "스타벅스",
                                                     name: "아메리카노",
                                                     expirationDate: "2022.08.15",
                                                     category: .cafe),
                              numberOfParticipants: 0,
                              isParticipating: false),
                 GifticonCard(sprinkleTime: "2022.08.14",
                              gifticonInfo: Gifticon(id: 2,
                                                     brand: "스타벅스",
                                                     name: "아메리카노",
                                                     expirationDate: "2022.08.15",
                                                     category: .cafe),
                              numberOfParticipants: 1,
                              isParticipating: true),
                 GifticonCard(sprinkleTime: "2022.08.15",
                              gifticonInfo: Gifticon(id: 3,
                                                     brand: "스타벅스",
                                                     name: "아메리카노",
                                                     expirationDate: "2022.08.15",
                                                     category: .cafe),
                              numberOfParticipants: 1,
                              isParticipating: false)
            ]),
            .category(Category.allCases),
            .gifticonList([
                GifticonCard(sprinkleTime: "2022.08.12",
                              gifticonInfo: Gifticon(id: 0,
                                                     brand: "스타벅스",
                                                     name: "아메리카노",
                                                     expirationDate: "2022.08.15",
                                                     category: .cafe),
                              numberOfParticipants: 12342,
                              isParticipating: false),
                 GifticonCard(sprinkleTime: "2022.08.13",
                              gifticonInfo: Gifticon(id: 1,
                                                     brand: "스타벅스",
                                                     name: "아메리카노",
                                                     expirationDate: "2022.08.15",
                                                     category: .cafe),
                              numberOfParticipants: 0,
                              isParticipating: false),
                 GifticonCard(sprinkleTime: "2022.08.14",
                              gifticonInfo: Gifticon(id: 2,
                                                     brand: "스타벅스",
                                                     name: "아메리카노",
                                                     expirationDate: "2022.08.15",
                                                     category: .cafe),
                              numberOfParticipants: 1,
                              isParticipating: true),
                 GifticonCard(sprinkleTime: "2022.08.15",
                              gifticonInfo: Gifticon(id: 3,
                                                     brand: "스타벅스",
                                                     name: "아메리카노",
                                                     expirationDate: "2022.08.15",
                                                     category: .cafe),
                              numberOfParticipants: 1,
                              isParticipating: false)])]
    static let myBox = [GifticonCard(sprinkleTime: "2022.08.12",
                                     gifticonInfo: Gifticon(id: 0,
                                                            brand: "스타벅스",
                                                            name: "아메리카노",
                                                            expirationDate: "2022.08.15",
                                                            category: .cafe),
                                     numberOfParticipants: 12342,
                                     isParticipating: false),
                        GifticonCard(sprinkleTime: "2022.08.13",
                                     gifticonInfo: Gifticon(id: 1,
                                                            brand: "스타벅스",
                                                            name: "아메리카노",
                                                            expirationDate: "2022.08.15",
                                                            category: .cafe),
                                     numberOfParticipants: 0,
                                     isParticipating: false),
                        GifticonCard(sprinkleTime: "2022.08.14",
                                     gifticonInfo: Gifticon(id: 2,
                                                            brand: "스타벅스",
                                                            name: "아메리카노",
                                                            expirationDate: "2022.08.15",
                                                            category: .cafe),
                                     numberOfParticipants: 1,
                                     isParticipating: true),
                        GifticonCard(sprinkleTime: "2022.08.15",
                                     gifticonInfo: Gifticon(id: 3,
                                                            brand: "스타벅스",
                                                            name: "아메리카노",
                                                            expirationDate: "2022.08.15",
                                                            category: .cafe),
                                     numberOfParticipants: 1,
                                     isParticipating: false)]
}
